Models/BeneficiosFuncionario.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Web;

namespace PowerTecWeb.Models
{
    public class BeneficiosFuncionario
    {
        
        public int IdFuncionarioBeneficio { get; set; }
        [DisplayName("Funcionario Solicitante")]
        public Nullable<int> IdFuncionario { get; set; }
        [DisplayName("Beneficio")]
        public Nullable<int> IdBeneficio { get; set; }
        public string Aprovado { get; set; }

        public virtual tbBeneficio tbBeneficio { get; set; }
        public virtual tbFuncionario tbFuncionario { get; set; }
    }
}

Controllers/BeneficiosFuncionarioController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PowerTecWeb;

namespace PowerTecWeb.Controllers
{
    public class BeneficiosFuncionarioController : Controller
    {
        private PowerTecEntities db = new PowerTecEntities();

        // GET: BeneficiosFuncionario
        public ActionResult Index(int? id)
        {
            var tbFuncionarioBeneficio = db.tbFuncionarioBeneficio.Include(t => t.tbBeneficio).Include(t => t.tbFuncionario);
            return View(tbFuncionarioBeneficio.Where(d=>d.IdFuncionario == id).ToList());
        }

        // GET: BeneficiosFuncionario/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbFuncionarioBeneficio tbFuncionarioBeneficio = db.tbFuncionarioBeneficio.Find(id);
            if (tbFuncionarioBeneficio == null)
            {
                return HttpNotFound();
            }
            return View(tbFuncionarioBeneficio);
        }

        // GET: BeneficiosFuncionario/Create
        public ActionResult Create()
        {
            ViewBag.IdBeneficio = new SelectList(db.tbBeneficio, "IdBeneficio", "Nome");
            ViewBag.IdFuncionario = new SelectList(db.tbFuncionario, "IdFuncionario", "Nome_completo");
            return View();
        }

        // POST: BeneficiosFuncionario/Create
        // Para se proteger de mais ataques, habilite as propriedades específicas às quais você quer se associar. Para 
        // obter mais detalhes, veja https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdFuncionarioBeneficio,IdFuncionario,IdBeneficio")] tbFuncionarioBeneficio tbFuncionarioBeneficio)
        {
            tbFuncionarioBeneficio.Aprovado = "N";
            if (ModelState.IsValid)
            {
                db.tbFuncionarioBeneficio.Add(tbFuncionarioBeneficio);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.IdBeneficio = new SelectList(db.tbBeneficio, "IdBeneficio", "Nome", tbFuncionarioBeneficio.IdBeneficio);
            ViewBag.IdFuncionario = new SelectList(db.tbFuncionario, "IdFuncionario", "Nome_completo", tbFuncionarioBeneficio.IdFuncionario);
            return View(tbFuncionarioBeneficio);
        }

        // GET: BeneficiosFuncionario/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbFuncionarioBeneficio tbFuncionarioBeneficio = db.tbFuncionarioBeneficio.Find(id);
            if (tbFuncionarioBeneficio == null)
            {
                return HttpNotFound();
            }
            ViewBag.IdBeneficio = new SelectList(db.tbBeneficio, "IdBeneficio", "Nome", tbFuncionarioBeneficio.IdBeneficio);
            ViewBag.IdFuncionario = new SelectList(db.tbFuncionario, "IdFuncionario", "Nome_completo", tbFuncionarioBeneficio.IdFuncionario);
            return View(tbFuncionarioBeneficio);
        }

        // POST: BeneficiosFuncionario/Edit/5
        // Para se proteger de mais ataques, habilite as propriedades específicas às quais você quer se associar. Para 
        // obter mais detalhes, veja https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdFuncionarioBeneficio,IdFuncionario,IdBeneficio,Aprovado")] tbFuncionarioBeneficio tbFuncionarioBeneficio)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tbFuncionarioBeneficio).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("IndexColaborador","AreaColaborador");
            }
            ViewBag.IdBeneficio = new SelectList(db.tbBeneficio, "IdBeneficio", "Nome", tbFuncionarioBeneficio.IdBeneficio);
            ViewBag.IdFuncionario = new SelectList(db.tbFuncionario, "IdFuncionario", "Nome_completo", tbFuncionarioBeneficio.IdFuncionario);
            return View(tbFuncionarioBeneficio);
        }

        // GET: BeneficiosFuncionario/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbFuncionarioBeneficio tbFuncionarioBeneficio = db.tbFuncionarioBeneficio.Find(id);
            if (tbFuncionarioBeneficio == null)
            {
                return HttpNotFound();
            }
            return View(tbFuncionarioBeneficio);
        }

        // POST: BeneficiosFuncionario/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            tbFuncionarioBeneficio tbFuncionarioBeneficio = db.tbFuncionarioBeneficio.Find(id);
            db.tbFuncionarioBeneficio.Remove(tbFuncionarioBeneficio);
            db.SaveChanges();
            return RedirectToAction("IndexColaborador","AreaColaborador");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/BeneficiosFuncionario/Create.cshtml
@model PowerTecWeb.tbFuncionarioBeneficio

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutColaborador.cshtml";
}

<h2>Cadastrar</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
                <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.IdFuncionario, "Funcionário solicitante", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdFuncionario", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdFuncionario, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdBeneficio, "Beneficio", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdBeneficio", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdBeneficio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Solicitar beneficio" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar", "IndexColaborador","AreaColaborador")
</div>

Views/BeneficiosFuncionario/Details.cshtml
@model PowerTecWeb.tbFuncionarioBeneficio

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutColaborador.cshtml";
}

<h2>Detalhes</h2>

<div>
        <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.tbBeneficio.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tbBeneficio.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tbFuncionario.Nome_completo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tbFuncionario.Nome_completo)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.IdFuncionarioBeneficio }) |
    @Html.ActionLink("Voltar", "IndexColaborador","AreaColaborador")
</p>

Views/BeneficiosFuncionario/Edit.cshtml
@model PowerTecWeb.tbFuncionarioBeneficio

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutColaborador.cshtml";
}

<h2>Alteração</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.IdFuncionarioBeneficio)

    <div class="form-group">
        @Html.LabelFor(model => model.IdFuncionario, "Funcionário Solicitante", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("IdFuncionario", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.IdFuncionario, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.IdBeneficio, "Beneficio", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("IdBeneficio", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.IdBeneficio, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Aprovado, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.ValidationMessageFor(model => model.Aprovado, "", new { @class = "text-danger" })
            <span>Sim </span>
            @Html.RadioButtonFor(m => m.Aprovado, "S", new { onclick = "return false" })
            <span>Não </span>
            @Html.RadioButtonFor(m => m.Aprovado, "N", new { @checked = true, onclick = "return false" })
        </div>
    </div>


    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Salvar" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Voltar", "IndexColaborador","AreaColaborador")
</div>

Views/BeneficiosFuncionario/Index.cshtml
@model IEnumerable<PowerTecWeb.tbFuncionarioBeneficio>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutColaborador.cshtml";
}

<h2>Meus Beneficios</h2>

<p>
    @Html.ActionLink("Solicitar beneficio", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.tbBeneficio.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.tbBeneficio.Valor)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.tbFuncionario.Nome_completo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Aprovado)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.tbBeneficio.Nome)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.tbBeneficio.Valor)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.tbFuncionario.Nome_completo)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Aprovado)
    </td>
    <td>
        <a href="@Url.Action("Edit","BeneficiosFuncionario", new { id = item.IdFuncionarioBeneficio })"> Editar|</a>
        <a href="@Url.Action("Details","BeneficiosFuncionario", new { id = item.IdFuncionarioBeneficio })"> Detalhes|</a>
        @*<a href="@Url.Action("Delete","BeneficiosFuncionario", new { id = item.IdFuncionarioBeneficio }) "> Deletar|</a>*@
    </td>
</tr>
}

</table>