Controllers/FeriasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PowerTecWeb;

namespace PowerTecWeb.Views.AreaGerente
{
    public class FeriasController : Controller
    {
        private PowerTecEntities db = new PowerTecEntities();

        // GET: Ferias
        public ActionResult Index()
        {
            var tbFerias = db.tbFerias.Include(t => t.tbFuncionario);
            return View(tbFerias.ToList());
        }

        // GET: Ferias/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbFerias tbFerias = db.tbFerias.Find(id);
            if (tbFerias == null)
            {
                return HttpNotFound();
            }
            return View(tbFerias);
        }

        // GET: Ferias/Create
        public ActionResult SolicitarFerias()
        {
            ViewBag.IdFuncionario = new SelectList(db.tbFuncionario, "IdFuncionario", "Nome_completo",Session["IdFuncionario"]);
            return View();
        }

        // POST: Ferias/Create
        // Para se proteger de mais ataques, habilite as propriedades específicas às quais você quer se associar. Para 
        // obter mais detalhes, veja https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdFerias,Data_Inicio,Data_Fim,Aprovado,IdFuncionario")] tbFerias tbFerias)
        {
            if (ModelState.IsValid)
            {
                db.tbFerias.Add(tbFerias);
                db.SaveChanges();
                return RedirectToAction("IndexColaborador", "AreaColaborador");
            }

            ViewBag.IdFuncionario = new SelectList(db.tbFuncionario, "IdFuncionario", "Nome_completo", tbFerias.IdFuncionario);
            return RedirectToAction("IndexColaborador","AreaColaborador");
        }

        // GET: Ferias/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbFerias tbFerias = db.tbFerias.Find(id);
            if (tbFerias == null)
            {
                return HttpNotFound();
            }
            ViewBag.IdFuncionario = new SelectList(db.tbFuncionario, "IdFuncionario", "Nome_completo", tbFerias.IdFuncionario);
            return View(tbFerias);
        }

        // POST: Ferias/Edit/5
        // Para se proteger de mais ataques, habilite as propriedades específicas às quais você quer se associar. Para 
        // obter mais detalhes, veja https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdFerias,Data_Inicio,Data_Fim,Aprovado,IdFuncionario")] tbFerias tbFerias)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tbFerias).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("IndexColaborador", "AreaColaborador");
            }
            ViewBag.IdFuncionario = new SelectList(db.tbFuncionario, "IdFuncionario", "Nome_completo", tbFerias.IdFuncionario);
            return View(tbFerias);
        }

        // GET: Ferias/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbFerias tbFerias = db.tbFerias.Find(id);
            if (tbFerias == null)
            {
                return HttpNotFound();
            }
            return View(tbFerias);
        }

        // POST: Ferias/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            tbFerias tbFerias = db.tbFerias.Find(id);
            db.tbFerias.Remove(tbFerias);
            db.SaveChanges();
            return RedirectToAction("IndexColaborador", "AreaColaborador");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/FuncionariosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PowerTecWeb;

namespace PowerTecWeb.Controllers
{
    public class FuncionariosController : Controller
    {
        private PowerTecEntities db = new PowerTecEntities();

        // GET: Funcionarios
        public ActionResult Index()
        {
            var tbFuncionario = db.tbFuncionario.Include(t => t.tbCargo);
            return View(tbFuncionario.ToList());
        }

        // GET: Funcionarios/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbFuncionario tbFuncionario = db.tbFuncionario.Find(id);
            if (tbFuncionario == null)
            {
                return HttpNotFound();
            }
            return View(tbFuncionario);
        }

        // GET: Funcionarios/Create
        public ActionResult Create()
        {
            ViewBag.IdCargo = new SelectList(db.tbCargo, "IdCargo", "Nome");

            List<SelectListItem> items = new List<SelectListItem>();

            items.Add(new SelectListItem { Text = "Funcionario", Value = "0" });

            items.Add(new SelectListItem { Text = "Administrador", Value = "1" });


            ViewBag.Niveis = items;
            return View();
        }

        // POST: Funcionarios/Create
        // Para se proteger de mais ataques, habilite as propriedades específicas às quais você quer se associar. Para 
        // obter mais detalhes, veja https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdFuncionario,Nome_completo,Cpf,Rg,Telefone,Email,Estado_civil,Salario,Data_admissao,Jornada_trabalho,Tipo_contrato,Banco_agencia,Numero_conta,NivelAcesso,IdCargo,Usuario,Senha,Logradouro,Numero,Complemento,Bairro,Cidade,Estado,Cep")] tbFuncionario tbFuncionario)
        {
            if (ModelState.IsValid)
            {
                db.tbFuncionario.Add(tbFuncionario);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.IdCargo = new SelectList(db.tbCargo, "IdCargo", "Nome", tbFuncionario.IdCargo);
            return View(tbFuncionario);
        }

        // GET: Funcionarios/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbFuncionario tbFuncionario = db.tbFuncionario.Find(id);
            if (tbFuncionario == null)
            {
                return HttpNotFound();
            }
            ViewBag.IdCargo = new SelectList(db.tbCargo, "IdCargo", "Nome", tbFuncionario.IdCargo);
            return View(tbFuncionario);
        }

        // POST: Funcionarios/Edit/5
        // Para se proteger de mais ataques, habilite as propriedades específicas às quais você quer se associar. Para 
        // obter mais detalhes, veja https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdFuncionario,Nome_completo,Cpf,Rg,Telefone,Email,Estado_civil,Salario,Data_admissao,Jornada_trabalho,Tipo_contrato,Banco_agencia,Numero_conta,NivelAcesso,IdCargo,Usuario,Senha,Logradouro,Numero,Complemento,Bairro,Cidade,Estado,Cep")] tbFuncionario tbFuncionario)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tbFuncionario).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.IdCargo = new SelectList(db.tbCargo, "IdCargo", "Nome", tbFuncionario.IdCargo);
            return View(tbFuncionario);
        }

        // GET: Funcionarios/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbFuncionario tbFuncionario = db.tbFuncionario.Find(id);
            if (tbFuncionario == null)
            {
                return HttpNotFound();
            }
            return View(tbFuncionario);
        }

        // POST: Funcionarios/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            tbFuncionario tbFuncionario = db.tbFuncionario.Find(id);
            db.tbFuncionario.Remove(tbFuncionario);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult MeuCadastro(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("LoginColaborador", "Home");
            }
            tbFuncionario tbFuncionario = db.tbFuncionario.Find(id);
            if (tbFuncionario == null)
            {
                return HttpNotFound();
            }
            return View(tbFuncionario);
        }
        public ActionResult MeusDependentes(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("LoginColaborador", "Home");
            }
            var tbDependente = db.tbDependente.Include(t => t.tbFuncionario);
            tbDependente = tbDependente.Where(d => d.IdFuncionario == id);
            if (tbDependente == null)
            {
                return HttpNotFound();
            }
            return View(tbDependente);
        }


        public ActionResult MeusComprovantes(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("LoginColaborador", "Home");
            }

            var tbHolerite = db.tbHolerite.Include(t => t.tbFuncionario);
            return View(tbHolerite.Where(d => d.IdFuncionario == id).ToList());




        }

        public ActionResult MeusChamados(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("LoginColaborador", "Home");
            }
            var tbChamado = db.tbChamado.Include(t => t.tbFuncionario);
            tbChamado = tbChamado.Where(d => d.IdFuncionario == id);
            return View(tbChamado.ToList());
        }

        public ActionResult MinhasFerias(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("LoginColaborador", "Home");
            }
            var tbFerias = db.tbFerias.Include(t => t.tbFuncionario);
            tbFerias = tbFerias.Where(d => d.IdFuncionario == id);
            return View(tbFerias.ToList());
        }

        public ActionResult Logout()
        {
            Session.RemoveAll();
            return RedirectToAction("Index", "Home");

        }
        public ActionResult MeuPonto(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("LoginColaborador", "Home");
            }
            var tbPonto = db.tbPonto.Include(t => t.tbFuncionario);
            tbPonto = tbPonto.Where(d => d.IdFuncionario == id);
            return View(tbPonto.ToList());
        }
    }
}

Controllers/PontosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PowerTecWeb;

namespace PowerTecWeb.Controllers
{
    public class PontosController : Controller
    {
        private PowerTecEntities db = new PowerTecEntities();

        // GET: Pontos
        public ActionResult Index()
        {
            var id = Convert.ToInt32(Session["IdFuncionario"]);
            var tbPonto = db.tbPonto.Include(t => t.tbFuncionario).Where(d=> d.IdFuncionario == id);
            return View(tbPonto.ToList());
        }

        // GET: Pontos/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbPonto tbPonto = db.tbPonto.Find(id);
            if (tbPonto == null)
            {
                return HttpNotFound();
            }
            return View(tbPonto);
        }

        // GET: Pontos/Create
        public ActionResult Create()
        {
            ViewBag.IdFuncionario = new SelectList(db.tbFuncionario, "IdFuncionario", "Nome_completo", Session["IdFuncionario"]);
            return View();
        }

        // POST: Pontos/Create
        // Para se proteger de mais ataques, habilite as propriedades específicas às quais você quer se associar. Para 
        // obter mais detalhes, veja https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdPonto,Data_entrada,Data_saida,Saida_almoco,Hora_extra,Feriado,IdFuncionario")] tbPonto tbPonto)
        {
            if (ModelState.IsValid)
            {
                db.tbPonto.Add(tbPonto);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.IdFuncionario = new SelectList(db.tbFuncionario, "IdFuncionario", "Nome_completo", tbPonto.IdFuncionario);
            return RedirectToAction("MeuPonto","Funcionarios",new { id = Session["IdFuncionario"]});
        }

        // GET: Pontos/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbPonto tbPonto = db.tbPonto.Find(id);
            if (tbPonto == null)
            {
                return HttpNotFound();
            }
            ViewBag.IdFuncionario = new SelectList(db.tbFuncionario, "IdFuncionario", "Nome_completo", tbPonto.IdFuncionario);
            return View(tbPonto);
        }

        // POST: Pontos/Edit/5
        // Para se proteger de mais ataques, habilite as propriedades específicas às quais você quer se associar. Para 
        // obter mais detalhes, veja https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdPonto,Data_entrada,Data_saida,Saida_almoco,Hora_extra,Feriado,IdFuncionario")] tbPonto tbPonto)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tbPonto).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.IdFuncionario = new SelectList(db.tbFuncionario, "IdFuncionario", "Nome_completo", tbPonto.IdFuncionario);
            return View(tbPonto);
        }

        // GET: Pontos/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbPonto tbPonto = db.tbPonto.Find(id);
            if (tbPonto == null)
            {
                return HttpNotFound();
            }
            return View(tbPonto);
        }

        // POST: Pontos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            tbPonto tbPonto = db.tbPonto.Find(id);
            db.tbPonto.Remove(tbPonto);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Funcionarios/Delete.cshtml
@model PowerTecWeb.tbFuncionario

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutColaborador.cshtml";
}

<h2>Excluir</h2>

<h3>Tem certeza que deseja excluir o registro selecionado:<
<div>
    <h4>tbFuncionario</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nome_completo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome_completo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cpf)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cpf)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Rg)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Rg)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Telefone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Telefone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Estado_civil)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Estado_civil)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Salario)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Salario)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Data_admissao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Data_admissao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Jornada_trabalho)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Jornada_trabalho)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tipo_contrato)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tipo_contrato)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Banco_agencia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Banco_agencia)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Numero_conta)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Numero_conta)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NivelAcesso)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NivelAcesso)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Usuario)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Usuario)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Senha)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Senha)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Logradouro)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Logradouro)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Numero)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Numero)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Complemento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Complemento)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Bairro)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Bairro)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cidade)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cidade)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Estado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Estado)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cep)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cep)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tbCargo.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tbCargo.Nome)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Excluir" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/Funcionarios/Index.cshtml
@model IEnumerable<PowerTecWeb.tbFuncionario>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutColaborador.cshtml";
}


<p>
    @Html.ActionLink("Cadastrar", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nome_completo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Cpf)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Rg)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Telefone)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.tbCargo.Nome)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nome_completo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Cpf)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Rg)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Telefone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.tbCargo.Nome)
            </td>
            <td>
                @Html.ActionLink("Editar", "Edit", new { id = item.IdFuncionario }) |
                @Html.ActionLink("Detalhes", "Details", new { id = item.IdFuncionario }) |
                @Html.ActionLink("Excluir", "Delete", new { id = item.IdFuncionario }) |
               <a href= "@Url.Action("Create", "Dependentes", new { id = item.IdFuncionario })">Inserir Dependente</a> 
            </td>
        </tr>
    }

</table>

Views/Funcionarios/MeuPonto.cshtml
@model IEnumerable<PowerTecWeb.tbPonto>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutColaborador.cshtml";
}

<h2>Meu ponto</h2>

<p>
    @Html.ActionLink("Lançar ponto", "Create","Pontos")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Data_entrada)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Data_saida)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Saida_almoco)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Hora_extra)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Feriado)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.tbFuncionario.Nome_completo)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Data_entrada)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Data_saida)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Saida_almoco)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Hora_extra)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Feriado)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.tbFuncionario.Nome_completo)
        </td>
        <td>
            <a href="@Url.Action("Edit","Pontos",new { id = item.IdPonto})">Editar |</a>
            <a href="@Url.Action("Details","Pontos",new { id = item.IdPonto})">Detalhes |</a>
        </td>
    </tr>
}

</table>

Views/Funcionarios/MeusChamados.cshtml
@model IEnumerable<PowerTecWeb.tbChamado>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutColaborador.cshtml";
}

<h2>Meus Chamados</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Assunto)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Mensagem)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Data_chamado)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.tbFuncionario.Nome_completo)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Assunto)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Mensagem)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Data_chamado)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.tbFuncionario.Nome_completo)
        </td>
        <td>
            <a href="@Url.Action("Details", "Chamados", new { id = item.IdChamado })"> Detalhes </a>
        </td>
    </tr>
}

</table>

Views/Funcionarios/MinhasFerias.cshtml
@model IEnumerable<PowerTecWeb.tbFerias>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutColaborador.cshtml";
}

<h2>Minhas férias</h2>

<p>
    @Html.ActionLink("Solicitar férias", "SolicitarFerias","Ferias")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Data_Inicio)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Data_Fim)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Aprovado)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.tbFuncionario.Nome_completo)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Data_Inicio)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Data_Fim)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Aprovado)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.tbFuncionario.Nome_completo)
        </td>
        <td>
            <a href="@Url.Action("Edit", "Ferias", new { id = item.IdFerias })">Editar</a>  |
            <a href="@Url.Action("Details", "Ferias", new { id = item.IdFerias })"> Detalhes </a>
        </td>
    </tr>
}

</table>