Models/ComprovantesPagamento.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace PowerTecWeb.Models
{
    public class ComprovantesPagamento
    {

   
        public int IdHolerite { get; set; }

        [DisplayName("Data inicial")]
        [DataType(DataType.Date)]
        public DateTime DataInicial { get; set; }
        [DataType(DataType.Date)]
        [DisplayName("Data final")]
        public DateTime DataFinal { get; set; }
        [DisplayName("Salário base")]
        public decimal Salario_base { get; set; }
        [DisplayName("Horas extras")]
        public decimal Horas_extras { get; set; }
        [DisplayName("Comissões")]
        public decimal Comissoes { get; set; }
        [DisplayName("Outros proventos")]
        public decimal Outros_proventos { get; set; }

        [DisplayName("Total proventos")]
        public decimal Total_proventos { get; set; }
        [DisplayName("Plano de saúde")]
        public decimal Plano_saude { get; set; }
        [DisplayName("Vale transporte")]
        public Nullable<decimal> Vale_transporte { get; set; }

        [DisplayName("Total de deduções")]
        public Nullable<decimal> Total_deducoes { get; set; }
        [DisplayName("Valor liquido")]
        public decimal Valor_liquido { get; set; }
        public decimal Ferias { get; set; }

        [DisplayName("Aviso previo")]
        public Nullable<decimal> Aviso_previo { get; set; }
        [DisplayName("Beneficios adicionais")]
        public decimal Beneficios_adicionais { get; set; }

        [DisplayName("Outras informações")]
        public string Outras_Informacoes { get; set; }
        public Nullable<int> IdFuncionario { get; set; }

        public virtual tbFuncionario tbFuncionario { get; set; }
    }
}

Controllers/ComprovantesPagamentoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PowerTecWeb;

namespace PowerTecWeb.Controllers
{
    public class ComprovantesPagamentoController : Controller
    {
        private PowerTecEntities db = new PowerTecEntities();

        // GET: ComprovantesPagamento
        public ActionResult Index()
        {
            var tbHolerite = db.tbHolerite.Include(t => t.tbFuncionario);
            return View(tbHolerite.ToList());
        }

        // GET: ComprovantesPagamento/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbHolerite tbHolerite = db.tbHolerite.Find(id);
            if (tbHolerite == null)
            {
                return HttpNotFound();
            }
            return View(tbHolerite);
        }

        // GET: ComprovantesPagamento/Create
        public ActionResult Create()
        {
            ViewBag.IdFuncionario = new SelectList(db.tbFuncionario, "IdFuncionario", "Nome_completo");
            return View();
        }

        // POST: ComprovantesPagamento/Create
        // Para se proteger de mais ataques, habilite as propriedades específicas às quais você quer se associar. Para 
        // obter mais detalhes, veja https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdHolerite,DataInicial,DataFinal,Salario_base,Horas_extras,Comissoes,Outros_proventos,Total_proventos,Plano_saude,Vale_transporte,Total_deducoes,Valor_liquido,Ferias,Aviso_previo,Beneficios_adicionais,Outras_Informacoes,IdFuncionario")] tbHolerite tbHolerite)
        {
            if (ModelState.IsValid)
            {
                db.tbHolerite.Add(tbHolerite);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.IdFuncionario = new SelectList(db.tbFuncionario, "IdFuncionario", "Nome_completo", tbHolerite.IdFuncionario);
            return View(tbHolerite);
        }

        // GET: ComprovantesPagamento/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbHolerite tbHolerite = db.tbHolerite.Find(id);
            if (tbHolerite == null)
            {
                return HttpNotFound();
            }
            ViewBag.IdFuncionario = new SelectList(db.tbFuncionario, "IdFuncionario", "Nome_completo", tbHolerite.IdFuncionario);
            return View(tbHolerite);
        }

        // POST: ComprovantesPagamento/Edit/5
        // Para se proteger de mais ataques, habilite as propriedades específicas às quais você quer se associar. Para 
        // obter mais detalhes, veja https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdHolerite,DataInicial,DataFinal,Salario_base,Horas_extras,Comissoes,Outros_proventos,Total_proventos,Plano_saude,Vale_transporte,Total_deducoes,Valor_liquido,Ferias,Aviso_previo,Beneficios_adicionais,Outras_Informacoes,IdFuncionario")] tbHolerite tbHolerite)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tbHolerite).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.IdFuncionario = new SelectList(db.tbFuncionario, "IdFuncionario", "Nome_completo", tbHolerite.IdFuncionario);
            return View(tbHolerite);
        }

        // GET: ComprovantesPagamento/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbHolerite tbHolerite = db.tbHolerite.Find(id);
            if (tbHolerite == null)
            {
                return HttpNotFound();
            }
            return View(tbHolerite);
        }

        // POST: ComprovantesPagamento/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            tbHolerite tbHolerite = db.tbHolerite.Find(id);
            db.tbHolerite.Remove(tbHolerite);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/ComprovantesPagamento/Create.cshtml
@model PowerTecWeb.tbHolerite

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutColaborador.cshtml";
}

<h2>Cadastrar comprovante de pagamento</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.DataInicial, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DataInicial, new { htmlAttributes = new { @class = "form-control", type = "date" } })
            @Html.ValidationMessageFor(model => model.DataInicial, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.DataFinal, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DataFinal, new { htmlAttributes = new { @class = "form-control", type = "date" } })
            @Html.ValidationMessageFor(model => model.DataFinal, "", new { @class = "text-danger"})
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Salario_base, htmlAttributes: new { @class = "control-label col-md-2"})
        <div class="col-md-10">
            @Html.EditorFor(model => model.Salario_base, new { htmlAttributes = new { @class = "form-control", type = "number" ,min = "1" ,step = "any" , placeholder= "0" } })
            @Html.ValidationMessageFor(model => model.Salario_base, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Horas_extras, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Horas_extras, new { htmlAttributes = new { @class = "form-control", type = "number", min = "0", step = "any" , placeholder= "0" } })
            @Html.ValidationMessageFor(model => model.Horas_extras, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Comissoes, htmlAttributes: new { @class = "control-label col-md-2"})
        <div class="col-md-10">
            @Html.EditorFor(model => model.Comissoes, new { htmlAttributes = new { @class = "form-control", type = "number", min = "0", step = "any" , placeholder= "0" } })
            @Html.ValidationMessageFor(model => model.Comissoes, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Outros_proventos, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Outros_proventos, new { htmlAttributes = new { @class = "form-control", type = "number", min = "0", step = "any", placeholder= "0" } })
            @Html.ValidationMessageFor(model => model.Outros_proventos, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Total_proventos, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Total_proventos, new { htmlAttributes = new { @class = "form-control" , type = "number", min = "0", step = "any",placeholder= "0" } })
            @Html.ValidationMessageFor(model => model.Total_proventos, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Plano_saude, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Plano_saude, new { htmlAttributes = new { @class = "form-control", type = "number", min = "0", step = "any", placeholder= "0" } })
            @Html.ValidationMessageFor(model => model.Plano_saude, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Vale_transporte, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Vale_transporte, new { htmlAttributes = new { @class = "form-control" , placeholder= "0" } })
            @Html.ValidationMessageFor(model => model.Vale_transporte, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Total_deducoes, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Total_deducoes, new { htmlAttributes = new { @class = "form-control", type = "number", min = "0", step = "any", placeholder= "0" } })
            @Html.ValidationMessageFor(model => model.Total_deducoes, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Valor_liquido, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Valor_liquido, new { htmlAttributes = new { @class = "form-control" , type = "number", min = "0", step = "any", placeholder= "0" } })
            @Html.ValidationMessageFor(model => model.Valor_liquido, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Ferias, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Ferias, new { htmlAttributes = new { @class = "form-control", type = "number", min = "0", step = "any" , placeholder= "0" } })
            @Html.ValidationMessageFor(model => model.Ferias, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Aviso_previo, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Aviso_previo, new { htmlAttributes = new { @class = "form-control" , type = "number", min = "0", step = "any" , placeholder= "0" } })
            @Html.ValidationMessageFor(model => model.Aviso_previo, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Beneficios_adicionais, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Beneficios_adicionais, new { htmlAttributes = new { @class = "form-control", type = "number", min = "0", step = "any", placeholder= "0" } })
            @Html.ValidationMessageFor(model => model.Beneficios_adicionais, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Outras_Informacoes, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Outras_Informacoes, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Outras_Informacoes, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.IdFuncionario, "Funcionário", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("IdFuncionario", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.IdFuncionario, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Cadastrar" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Voltar", "Index")
</div>

Views/ComprovantesPagamento/Delete.cshtml
@model PowerTecWeb.tbHolerite

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutColaborador.cshtml";
}

<h2>Excluir</h2>

<h3>Tem certeza que deseja excluir o item selecionado?</h3>
<div>
    <h4>Comprovante de pagamento</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DataInicial)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataInicial)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DataFinal)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataFinal)
        </dd>


        <dt>
            @Html.DisplayNameFor(model => model.Salario_base)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Salario_base)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Horas_extras)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Horas_extras)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Comissoes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Comissoes)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Outros_proventos)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Outros_proventos)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Total_proventos)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Total_proventos)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Plano_saude)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Plano_saude)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Vale_transporte)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Vale_transporte)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Total_deducoes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Total_deducoes)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Valor_liquido)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Valor_liquido)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ferias)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ferias)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Aviso_previo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Aviso_previo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Beneficios_adicionais)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Beneficios_adicionais)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Outras_Informacoes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Outras_Informacoes)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tbFuncionario.Nome_completo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tbFuncionario.Nome_completo)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Excluir" class="btn btn-default" /> |
            @Html.ActionLink("Voltar", "Index")
        </div>
    }
</div>

Views/ComprovantesPagamento/Details.cshtml
@model PowerTecWeb.tbHolerite

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutColaborador.cshtml";
}

<h2>Detalhes</h2>

<div>
    <h4>Holerite</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DataInicial)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataInicial)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DataFinal)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataFinal)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Salario_base)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Salario_base)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Horas_extras)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Horas_extras)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Comissoes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Comissoes)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Outros_proventos)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Outros_proventos)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Total_proventos)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Total_proventos)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Plano_saude)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Plano_saude)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Vale_transporte)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Vale_transporte)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Total_deducoes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Total_deducoes)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Valor_liquido)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Valor_liquido)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ferias)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ferias)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Aviso_previo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Aviso_previo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Beneficios_adicionais)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Beneficios_adicionais)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Outras_Informacoes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Outras_Informacoes)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tbFuncionario.Nome_completo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tbFuncionario.Nome_completo)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Voltar", "IndexColaborador","AreaColaborador")
</p>

Views/ComprovantesPagamento/Index.cshtml
@model IEnumerable<PowerTecWeb.tbHolerite>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutColaborador.cshtml";
}

<h2>Comprovantes de pagamento</h2>

<p>
    @Html.ActionLink("Cadastrar", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.DataInicial)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.DataFinal)
        </th>
        <th>

            @Html.DisplayNameFor(model => model.Salario_base)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Horas_extras)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Comissoes)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Outros_proventos)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Total_proventos)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Plano_saude)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Vale_transporte)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Total_deducoes)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Valor_liquido)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Ferias)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Aviso_previo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Beneficios_adicionais)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Outras_Informacoes)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.tbFuncionario.Nome_completo)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.DataInicial)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.DataFinal)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Salario_base)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Horas_extras)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Comissoes)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Outros_proventos)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Total_proventos)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Plano_saude)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Vale_transporte)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Total_deducoes)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Valor_liquido)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Ferias)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Aviso_previo)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Beneficios_adicionais)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Outras_Informacoes)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.tbFuncionario.Nome_completo)
    </td>
    <td>
        <a href="@Url.Action("Edit","ComprovantesPagamento", new { id = item.IdHolerite })"> Editar|</a>
        <a href="@Url.Action("Details","ComprovantesPagamento", new { id = item.IdHolerite })"> Detalhes|</a>
    </td>
</tr>
}

</table>

Views/ComprovantesPagamento/MeusComprovantes.cshtml
@model IEnumerable<PowerTecWeb.tbHolerite>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutColaborador.cshtml";
}

<h2>Comprovantes de pagamento</h2>

<p>
    @Html.ActionLink("Cadastrar", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.DataInicial)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DataFinal)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Salario_base)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Horas_extras)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Comissoes)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Outros_proventos)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Total_proventos)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Plano_saude)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Vale_transporte)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Total_deducoes)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Valor_liquido)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Ferias)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Aviso_previo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Beneficios_adicionais)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Outras_Informacoes)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.tbFuncionario.Nome_completo)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.DataInicial)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.DataFinal)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Salario_base)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Horas_extras)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Comissoes)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Outros_proventos)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Total_proventos)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Plano_saude)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Vale_transporte)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Total_deducoes)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Valor_liquido)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Ferias)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Aviso_previo)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Beneficios_adicionais)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Outras_Informacoes)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.tbFuncionario.Nome_completo)
    </td>
    <td>
        
        <a href="@Url.Action("Details","ComprovantesPagamento",new { id = item.IdHolerite})">Detalhes |</a>
    </td>
</tr>
}

</table>